# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports = [ 
    # (modulesPath + "/installer/scan/not-detected.nix")
    ./disko-config.nix
  ];

  services.udev.extraRules = ''
    # SteelSeries Aerox 3 Wireless (wired mode)
    SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="183a", MODE="0666"
    SUBSYSTEM=="usb", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="183a", MODE="0666"

    # SteelSeries Aerox 3 Wireless (2.4 GHz wireless mode)
    SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="1838", MODE="0666"
    SUBSYSTEM=="usb", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="1838", MODE="0666"

    # HDD
    ACTION=="add|change", KERNEL=="sd[a-z]*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"

    # SSD
    ACTION=="add|change", KERNEL=="sd[a-z]*|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="bfq"

    # NVMe SSD
    ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"

    # SATA Active Link Power Management
    ACTION=="add", SUBSYSTEM=="scsi_host", KERNEL=="host*", \
        ATTR{link_power_management_policy}=="*", \
        ATTR{link_power_management_policy}="max_performance"
    
  '';

  # NO TPM
  services.tcsd.enable = lib.mkDefault false;
  systemd.tpm2.enable = lib.mkDefault false;
  boot.initrd.systemd.tpm2.enable = lib.mkDefault false;

  boot = {

    supportedFilesystems = [ "ntfs" ];
    
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    kernelModules = [ "kvm-amd" "k10temp" ];
    extraModulePackages = [ config.boot.kernelPackages.zenergy ];
    blacklistedKernelModules = [ ];

    kernelParams = [ "amd_pstate=active" ];

    kernel.sysctl = {

      # Memory
			# Disable swap read ahead, increases latency when dealing with swap and it's rather meaningless when using zram+zstd anyway
			"vm.page-cluster" = 0;
			# Hugepages configuration, mostly for xmrig
			# Not needed anymore
			# "vm.nr_hugepages" = 25;
			# "vm.nr_overcommit_hugepages" = 150;
			# Prefer to keep filesystem cache memory over application memory
			"vm.vfs_cache_pressure" = 200;
			# Proper swappiness
			"vm.swappiness" = 10;
      # Contains, as bytes, the number of pages at which a process which is
      # generating disk writes will itself start writing out dirty data.
      # "vm.dirty_bytes" = 268435456;
      # Contains, as bytes, the number of pages at which the background kernel
      # flusher threads will start writing out dirty data.
      # "vm.dirty_background_bytes" = 67108864;
      # The kernel flusher threads will periodically wake up and write old data out to disk.  This
      # tunable expresses the interval between those wakeups, in 100'ths of a second (Default is 500).
      # "vm.dirty_writeback_centisecs" = 1500;
			# Best value, according to phoronix
			# "vm.page_lock_unfairness" = 1;
			# Disable watermark boosting
			"vm.watermark_boost_factor" = 0; # Needed when not using the zen-kernel
			# Increase kswapd activity
			# When free memory is less than 1.5%, make kswapd kick in.
			# https://unix.stackexchange.com/a/679203
			"vm.watermark_scale_factor" = 500;

      "vm.dirty_background_ratio" = 5;
      "vm.dirty_ratio" = 10;

    };
  };

  powerManagement.cpuFreqGovernor = "performance";

  services.fstrim.enable = lib.mkDefault true;

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 100;
    priority = 100;
  };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/df022cf4-ed2f-4883-8da1-b5161367a8ea";
      fsType = "btrfs";
      options = [ "compress=zstd:1" "noatime" "discard=async" ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = lib.mkDefault true;
}
