{ config, lib, pkgs, inputs, ... }: 

{

  options = {
    hyprland.setup =
      lib.mkEnableOption "Enables and configure Hyprland";
  };

  config = lib.mkIf config.hyprland.setup {

    # programs.zsh.initContent = ''
    #   if uwsm check may-start 1>/dev/null; then
    #     exec uwsm start hyprland-uwsm.desktop
    #   fi
    # '';

    stylix.targets.hyprland.enable = false;

    wayland.windowManager.hyprland = {
      
      enable = true;
      systemd.enable = false;
      package = null; # Package managed from NixOS
      portalPackage = null;
      
      plugins = with pkgs.hyprlandPlugins; [
        hypr-dynamic-cursors
        hyprsplit
      ];

      settings = {
        
        autogenerated = 0;
        # env = [
        #   "XCURSOR_THEME,catppuccin-mocha-dark-cursors"
        #   "XCURSOR_SIZE,24"
        #   "HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors"
        #   "HYPRCURSOR_SIZE,32"
        # ];

        source = [
          "$HOME/.config/hypr/config/keybindings.conf"
          "$HOME/.config/hypr/config/rules.conf"
          "$HOME/.config/hypr/themes/mocha.conf"
        ];
        monitor = [
          "DP-1, 2560x1440@164.64, 0x0, 1"
          "DP-2, 1920x1080@143.99, -1920x360, 1"
        ];

        # ... other settings ...
        exec-once = [
          "systemctl --user enable --now hyprpolkitagent"
          "ags-start"

          "[workspace 5 silent] app2unit -s a -- Telegram"
          
          "sleep 3 && xrandr --output DP-1 --primary"
        ];

        #####################
        ### LOOK AND FEEL ###
        #####################

        # Refer to https://wiki.hyprland.org/Configuring/Variables/

        # https://wiki.hyprland.org/Configuring/Variables/#general
        general = { 

          gaps_in = 0;
          gaps_out = 0;

          border_size = 0;
          "col.active_border" = "$mauve $sapphire 45deg";
          "col.inactive_border" = "$overlay0";
          # Set to true enable resizing windows by clicking and dragging on borders and gaps
          resize_on_border = false;
          allow_tearing = true;
          layout = "master";

        };

        decoration = {

          rounding = 32;
          # Change transparency of focused and unfocused windows
          active_opacity = 1.0;
          inactive_opacity = 1.0;

          shadow = {

            enabled = false;
            range = 15;
            render_power = 3;
            color = "$surface0";

          };

          blur = {

            enabled = false;
            size = 9;
            # passes = 4;
            # new_optimizations = true;

          };
        };

        animations = {

          enabled = true;

          bezier = [
            "wind, 0.05, 0.9, 0.1, 1.05"
            "winIn, 0.1, 1.1, 0.1, 1.1"
            "winOut, 0.3, -0.3, 0, 1"
            "liner, 1, 1, 1, 1"
            # "bounce,1,1.6,0.1,0.85"
            # "slingshot,1,-1,0.15,1.25"
            # "nice,0,6.9,0.5,-4.20"
          ];
          animation = [
            "windows, 1, 6, wind, slide"
            "windowsIn, 1, 6, winIn, slide"
            "windowsOut, 1, 5, winOut, slide"
            "windowsMove, 1, 5, wind, slide"
            "fade, 1, 10, default"
            "workspaces, 1, 5, wind"
          ];

        };

        master = {

          mfact = 0.55;
          allow_small_split = true;

        };

        # dwindle = {

        #   pseudotile = true; # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        #   preserve_split = true; # You probably want this
        #   force_split = 2;

        # };

        #############
        ### INPUT ###
        #############

        input = {

          kb_layout = "us";
          kb_variant = "intl";
          kb_model = "";
          kb_options = "";
          kb_rules = "";
          follow_mouse = 1;

          mouse_refocus = false;
          sensitivity = 0; # -1.0 - 1.0, 0 means no modification.
          accel_profile = "flat";
        
        };

        cursor = {

          enable_hyprcursor = true;
          default_monitor = "DP-1";
          # inactive_timeout = 3;
          no_break_fs_vrr = 1;
          min_refresh_rate = 0;
          no_hardware_cursors = 1;
          use_cpu_buffer = 0;

        };

        ##############
        ### OTHERS ###
        ##############

        misc = { 

          force_default_wallpaper = 0; # Set to 0 or 1 to disable the anime mascot wallpapers
          disable_hyprland_logo = true; # If true disables the random hyprland logo / anime girl background. :(
          animate_manual_resizes = true;
          vfr = true;
          vrr = 3;
          close_special_on_empty = false;
          render_unfocused_fps = 60;
          enable_anr_dialog = false;

        };

        render = {
          
          explicit_sync = 1;
          explicit_sync_kms = 1;
          direct_scanout = 1;
          cm_fs_passthrough = 1;
        
        };
        # opengl.nvidia_anti_flicker = false;
        # debug.damage_tracking = 1;

        xwayland = {
          force_zero_scaling = true;
          # create_abstract_socket = true;
        };

        ecosystem = {
          no_update_news = true;
          no_donation_nag = true;
        };

        plugin = {
          hyprsplit = {
            num_workspaces = 4;
            persistent_workspaces = true;
          };

          dynamic-cursors = {
            shake.enabled = false;
            tilt.limit = 5750;

            shaperule = [
              "text, rotate:offset: 90"
              "grab, stretch, stretch:limit: 2000"
              # "clientside, none"
            ];
          };
        };

      };
    };

    # Hide GTK Window Title Buttons
    dconf.settings = {
      "org/gnome/desktop/wm/preferences".button-layout = "";
    };

    xdg = {
      configFile = {
        "hypr/config".source = ../config/hypr/config;
        "hypr/themes".source = ../config/hypr/themes;
        "hypr/scripts".source = ../config/hypr/scripts;
      };
    };
    
  };

}
