{ config, lib, pkgs, inputs, ... }:

{

  options = {
    hyprland.setup =
      lib.mkEnableOption "Enables and configure Hyprland";
  };

  config = lib.mkIf config.hyprland.setup {

    dunst.setup = false;
    waybar.setup = true;
    wofi.setup = false;

    programs.zsh.profileExtra = ''
      if uwsm check may-start; then
          exec uwsm start -S hyprland-uwsm.desktop
      fi
    '';

    stylix.targets.hyprland.enable = false;

    wayland.windowManager.hyprland = {
      
      enable = true;
      systemd = {
        enable = false;
        variables = ["--all"];
      };
      settings = {
        
        autogenerated = 0;
        env = [
          "XCURSOR_THEME,catppuccin-mocha-dark-cursors"
          "XCURSOR_SIZE,24"
          "HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors"
          "HYPRCURSOR_SIZE,32"
        ];

        source = [
          "$HOME/.config/hypr/config/keybindings.conf"
          "$HOME/.config/hypr/config/rules.conf"
          "$HOME/.config/hypr/themes/mocha.conf"
        ];
        monitor = [
          "DP-1,2560x1440@165, 1920x0, 1"
          "DP-2,1920x1080@144, 0x360, 1"
        ];

        exec-once = [
          "systemctl start --user polkit-gnome-authentication-agent-1"
          "uwsm app -- swww-daemon"
          "uwsm app -- clipse --listen & wl-clip-persist --clipboard regular"
          "$HOME/.scripts/start.sh"

          "[workspace 1 silent] uwsm app -- firefox"
          "[workspace 5 silent] uwsm app -- telegram-desktop"
          "[workspace 5 silent] uwsm app -- firefoxpwa site launch 01JHYC1SG0EHMC6QK9EGM6FXFM"

          "sleep 5 && xrandr --output DP-1 --primary"
        ];

        #####################
        ### LOOK AND FEEL ###
        #####################

        # Refer to https://wiki.hyprland.org/Configuring/Variables/

        # https://wiki.hyprland.org/Configuring/Variables/#general
        general = { 

          gaps_in = 10;
          gaps_out = 20;

          border_size = 3;
          "col.active_border" = "$mauve $sapphire 45deg";
          "col.inactive_border" = "$overlay0";
          # Set to true enable resizing windows by clicking and dragging on borders and gaps
          resize_on_border = false;
          allow_tearing = true;
          layout = "dwindle";

        };

        decoration = {

          rounding = 15;
          # Change transparency of focused and unfocused windows
          active_opacity = 1.0;
          inactive_opacity = 1.0;

          shadow = {

            enabled = true;
            range = 15;
            render_power = 3;
            color = "$surface0";

          };

          blur = {

            enabled = true;
            size = 9;
            passes = 4;
            new_optimizations = true;
            vibrancy = 0.1696;

          };
        };

        animations = {

          enabled = true;

          bezier = [
            "myBezier, 0.05, 0.9, 0.1, 1.05"
            "myBezier2, 0.65, 0, 0.35, 1"
            "slow,0,0.85,0.3,1"
            "overshot,0.7,0.6,0.1,1.1"
            "bounce,1,1.6,0.1,0.85"
            "slingshot,1,-1,0.15,1.25"
            "nice,0,6.9,0.5,-4.20"
          ];
          animation = [
            "windows,1,5,bounce,popin"
            "border,1,20,default"
            "fade,1,5,default"
            "workspaces,1,5,overshot,slide"
          ];

        };

        dwindle = {

          pseudotile = true; # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
          preserve_split = true; # You probably want this

        };

        #############
        ### INPUT ###
        #############

        input = {

          kb_layout = "us";
          kb_variant = "intl";
          kb_model = "";
          kb_options = "";
          kb_rules = "";

          mouse_refocus = false;
          sensitivity = 0; # -1.0 - 1.0, 0 means no modification.
          accel_profile = "flat";
        
        };

        cursor = {

          enable_hyprcursor = true;
          inactive_timeout = 3;
          no_hardware_cursors = 0;
          use_cpu_buffer = true;

        };

        ##############
        ### OTHERS ###
        ##############

        misc = { 

          force_default_wallpaper = 0; # Set to 0 or 1 to disable the anime mascot wallpapers
          disable_hyprland_logo = true; # If true disables the random hyprland logo / anime girl background. :(
          animate_manual_resizes = true;

        };

        render = {

          explicit_sync = 0;
          explicit_sync_kms = 0;
          direct_scanout = true;
        
        };
        # opengl.nvidia_anti_flicker = false;

        # xwayland = {
        #   force_zero_scaling = false;
        # };

      };
    };

    programs = {
      # hyprpanel = {
      #   enable = false;
      #   theme = "catppuccin_mocha";
      #   systemd.enable = true;
      #   hyprland.enable = true;
      #   overwrite.enable = true;

      #   override = {
      #     theme.bar.buttons = {
      #       notifications.background = "#1E1E2E";
      #       clock.background = "#1E1E2E";
      #       battery.background = "#1E1E2E";
      #       systray.background = "#1E1E2E";
      #       bluetooth.background = "#1E1E2E";
      #       network.background = "#1E1E2E";
      #       volume.background = "#1E1E2E";
      #       media.background = "#1E1E2E";
      #       windowtitle.background = "#1E1E2E";
      #       workspaces.background = "#1E1E2E";
      #       dashboard.background = "#1E1E2E";
      #       icon_background = "#1E1E2E";
      #       background = "#1E1E2E";
            
      #       modules = {
      #         power.background = "#1E1E2E";
      #         weather.background = "#1E1E2E";
      #         updates.background = "#1E1E2E";
      #         kbLayout.background = "#1E1E2E";
      #         netstat.background = "#1E1E2E";
      #         storage.background = "#1E1E2E";
      #         cpu.background = "#1E1E2E";
      #         cpuTemp.background = "#1E1E2E";
      #         ram.background = "#1E1E2E";
      #         submap.background = "#1E1E2E";
      #         submap.icon_background = "#1E1E2E";
      #         hyprsunset.background = "#1E1E2E";
      #         hyprsunset.icon_background = "#1E1E2E";
      #         hypridle.background = "#1E1E2E";
      #         cava.background = "#1E1E2E";
      #         cava.icon_background = "#1E1E2E";
      #       };
      #     };
      #   };

      #   layout = {
      #     "bar.layouts" = {
      #       "0" = {
      #         left = [ "dashboard" "workspaces" "windowtitle" ];
      #         middle = [ "media" ];
      #         right = [ "volume" "network" "clock" ];
      #       };
      #       "*" = {
      #         left = [ "workspaces" "windowtitle" ];
      #         middle = [ "cpu" "cputemp" "ram" "storage" ];
      #         right = [ "systray" "volume" "clock" "notifications" ];
      #       };
      #     };
      #   };

      #   settings = {
      #     scalingPriority = "hyprland";
      #     tear = true;

      #     theme = {
      #       osd.muted_zero = true;

      #       bar = {
      #         floating = true;
      #         transparent = true;
      #       };
      #     };

      #     bar = {
      #       launcher.autoDetectIcon = true;
      #       clock.format = "%a %b %d %I:%M %p";
      #       customModules.cpuTemp.sensor = "/sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input";
      #       volume = {
      #         rightClick = "${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
      #         middleClick = "${pkgs.pavucontrol}/bin/pavucontrol";
      #       };

      #       workspaces = {
      #         workspaces = 8;
      #         ignored = "-98";
      #       };
      #     };

      #     notifications = {
      #       active_monitor = false;
      #       showActionsOnHover = true;
      #       displayedTotal = 10;
      #       monitor = 1;
      #     };

      #     menus = let 
      #       sleepTry = "${pkgs.libnotify}/bin/notify-send 'Shut it down! >.<'";
      #     in {
      #       volume.raiseMaximumVolume = true;

      #       power = {
      #         showLabel = false;
      #         sleep = sleepTry;
      #       };

      #       dashboard = {
      #         controls.enabled = false;
      #         stats.enable_gpu = true;
      #         shortcuts.enabled = false;

      #         powermenu = let
      #           username = config.home.username;
      #           capitalize = str: "${lib.toUpper (builtins.substring 0 1 str)}${lib.toLower (builtins.substring 1 (builtins.stringLength str - 1) str)}";
      #         in {
      #           avatar.image = "/home/${config.home.username}/.face.icon";
      #           confirmation = false;
      #           logout = "uwsm stop";
      #           sleep = sleepTry;
      #           avatar.name = capitalize username;
      #         };
      #       };

      #       clock = {
      #         time.hideSeconds = true;

      #         weather = {
      #           key = "6837b6e8becd43ccb5922614243110";
      #           location = "Mao, Valverde";
      #           unit = "metric";
      #         };
      #       };
      #     };
      #   };
      # };

      fuzzel = {
        enable = true;
        settings = {
          main = {
            dpi-aware = "yes";
            prompt = "‎";
            launch-prefix = "uwsm app --";
            width = 50;
            inner-pad = 15;
            fields = "filename,name";
          };
        };
      };
    };
    

    home = {

      packages = with pkgs; [

        # Multimedia
        clipse
        playerctl

        # System Apps
        nautilus
        gnome-system-monitor
        gparted
        waypaper
        grim
        slurp
        swww
        lz4 # For compressing frames when animating
        wofi
        hyprpicker
        # hyprpanel

        wlr-randr
        wl-clipboard
        wl-clip-persist
        zenity

        hyprland-workspaces

      ];

      file = {

        ".config/hypr/config".source = ../config/hypr/config;
        ".config/hypr/themes".source = ../config/hypr/themes;
        ".config/hypr/scripts".source = ../config/hypr/scripts;
      };
    };

    # systemd.user.services = lib.mkIf config.programs.hyprpanel.systemd.enable {
    #   hyprpanel = {
    #     Unit = {
    #       Description = "A Bar/Panel for Hyprland with extensive customizability.";
    #       Documentation = "https://hyprpanel.com";
    #       PartOf = [ "graphical-session.target" ];
    #       After = [ "graphical-session-pre.target" ];
    #     };
    #     Service = {
    #       ExecStart = "${pkgs.hyprpanel}/bin/hyprpanel";
    #       ExecReload = "${pkgs.coreutils}/bin/kill -SIGUSR1 $MAINPID";
    #       Restart = "on-failure";
    #       KillMode = "mixed";
    #     };
    #     Install = { WantedBy = [ "graphical-session.target" ]; };
    #   };
    # };

    catppuccin.fuzzel.enable = false;

    # Hide GTK Window Title Buttons
    dconf.settings."org/gnome/desktop/wm/preferences".button-layout = "";

    xdg = {
      mimeApps = {
        enable = true;
        defaultApplications = {
          "inode/directory" = [ "org.gnome.Nautilus.desktop" ];
        };
        associations.removed = {
          "inode/directory" = "code.desktop";
        };
      };
    };
    
  };

}
