#################
### AUTOSTART ###
#################

exec-once = /home/faustrox/.dotfiles/home/scripts/autostart.zsh

exec-once = [workspace 1 silent] firefox
exec-once = [workspace 6 silent] telegram-desktop
exec-once = [workspace 6 silent] google-chrome-stable --app-id=hnpfjngllnobngcgfapefoaidbinmjnm
exec-once = [workspace 7 silent] steam
