#################
### AUTOSTART ###
#################

exec-once = swww-daemon
exec-once = swww img /home/faustrox/.dotfiles/assets/wallpapers/nix-black-4k.png
exec-once = dunst & waybar

exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only text data
exec-once = wl-clip-persist --clipboard regular

exec-once = [workspace 1 silent] firefox
exec-once = [workspace 6 silent] telegram-desktop
exec-once = [workspace 6 silent] google-chrome-stable --app-id=hnpfjngllnobngcgfapefoaidbinmjnm
exec-once = [workspace 7 silent] lutris
exec-once = [workspace 7 silent] steam

exec-once = easyeffects --gapplication-service
