
##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace = 1, monitor:DP-1, persistent:true, default:true
workspace = 2, monitor:DP-1, persistent:true
workspace = 3, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-1, persistent:true

workspace = 5, monitor:DP-2, persistent:true, default:true
workspace = 6, monitor:DP-2, persistent:true
workspace = 7, monitor:DP-2, persistent:true
workspace = 8, monitor:DP-2, persistent:true

windowrule = suppressevent maximize, class:.* # You'll probably like this.

windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Gaming

windowrule = tag +games, class:(^(gamescope)$|^(cs2)$|^(Minecraft.*)$|^(steam_app_.*)$)
windowrule = tag +games, onworkspace:2
windowrule = tag +unfocused, tag:games*

# windowrule = noborder, tag:games*
# windowrule = float, tag:games*
windowrule = noshadow, tag:games*
windowrule = noblur, tag:games*

windowrule = monitor DP-1, tag:games*
windowrule = workspace 2, tag:games*
windowrule = content game, tag:games*

# windowrule = fullscreen, tag:games
windowrule = immediate, tag:games*


# Other apps

windowrule = tag +unfocused, class:(^(.*)$)
windowrule = content video, class:stremio

windowrule = float, class:clipse
windowrule = size 622 652, class:clipse

windowrule = opacity 0.8 0.8, class:kitty
windowrule = opacity 0.8 0.8, class:Spotify
windowrule = float, class:qalculate-gtk

windowrule = float, class:com.github.hluk.copyq

# Misc

windowrule = renderunfocused, tag:unfocused*