
##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2

workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-1

# windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Tearing
windowrule = immediate, .*\.exe
windowrule = monitor DP-2, .*\.exe
windowrule = immediate, steam_app

# No shadow for tiled windows
# windowrulev2 = noshadow,floating:0

windowrule = opacity 0.8 0.8, ^(kitty)$
windowrule = opacity 0.8 0.8, ^(Spotify)$
windowrule = float, ^(kalk)$

windowrule = float, ^(com.github.hluk.copyq)$
