
##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace = 1, monitor:DP-1, persistent:true
workspace = 2, monitor:DP-1, persistent:true
workspace = 3, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-1, persistent:true

workspace = 5, monitor:DP-2, persistent:true
workspace = 6, monitor:DP-2, persistent:true
workspace = 7, monitor:DP-2, persistent:true
workspace = 8, monitor:DP-2, persistent:true

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Gaming

windowrulev2 = tag +games, class:(^(gamescope)$|^(cs2)$|^(Minecraft.*)$|^(steam_app_.*)$)
windowrulev2 = tag +unfocused, tag:games

windowrulev2 = float, tag:games
windowrulev2 = noborder, tag:games
windowrulev2 = noshadow, tag:games


windowrulev2 = monitor DP-1, tag:games
windowrulev2 = workspace 2, tag:games
# windowrulev2 = fullscreen, tag:games

windowrulev2 = immediate, fullscreen:1

# Other apps

windowrulev2 = tag +unfocused, class:stremio

windowrulev2 = float, class:clipse
windowrulev2 = size 622 652, class:clipse

windowrule = opacity 0.8 0.8, ^(kitty)$
windowrule = opacity 0.8 0.8, ^(Spotify)$
windowrule = float, ^(qalculate-gtk)$

windowrule = float, ^(com.github.hluk.copyq)$

# Misc

windowrulev2 = renderunfocused, tag:unfocused